container:
  image: cirrusci/android-sdk:29

check_task:
  # only_if: $BRANCH == "master"
  gradle_cache:
    folder: ~/.gradle/caches
  script: ./gradlew check
  cleanup_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -rf ~/.gradle/caches/transforms-1
    - rm -rf ~/.gradle/caches/journal-1
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
