name: Android Check

on:
  push:
    branches:
    - !deploy
    - *
    pull_request:
      paths: *

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check
      run: ./gradlew check
