name: Notify

on: check_suite

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
    - name: notify success to Telegram
      if: github.event.check_suite.conclusion == 'success'
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TelegramBotToken }}
        TELEGRAM_TO: ${{ secrets.TelegramTarget }}
        DEBUG: true
        FORMAT: markdown
      with:
        args: |
          "✅ [${{ github.repository }} build](${{ github.event.repository.html_url }}/actions) *${{ github.event.check_suite.conclusion }}*.

          `${{ github.ref }}` `${{ github.sha }}` by *${{ github.actor }}*

          ${{ github.event.check_suite.head_commit.message }}"
    - name: notify failure to Telegram
      if: github.event.check_suite.conclusion != 'success'
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TelegramBotToken }}
        TELEGRAM_TO: ${{ secrets.TelegramTarget }}
        DEBUG: true
        FORMAT: markdown
      with:
        args: |
          "🔴 [${{ github.repository }} build](${{ github.event.repository.html_url }}/actions) *${{ github.event.check_suite.conclusion }}*.

          `${{ github.ref }}` `${{ github.sha }}` by *${{ github.actor }}*

          ${{ github.event.check_suite.head_commit.message }}"
