name: Notify

on: check_suite

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
    - name: notify success to Telegram
      if: ${{ github.event.check_suite.conclusion }} == success
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TelegramBotToken }}
        TELEGRAM_TO: ${{ secrets.TelegramTarget }}
        DEBUG: true
        FORMAT: markdown
      with:
        args: |
        "✅[${{ github.event.repository.full_name }} #${{ github.event.check_suite.id }}](${{ github.event.check_suite.url }}) *${{ github.event.check_suite.conclusion }}*.

        `${{ github.event.check_suite.head_branch }}` `${{ github.event.check_suite.head_sha }}` by *${{ github.event.check_suite.head_commit.author.name }}*

        _${{ github.event.check_suite.head_commit.message }}_"
    - name: notify failure to Telegram
      if: ${{ github.event.check_suite.conclusion }} != success
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TelegramBotToken }}
        TELEGRAM_TO: ${{ secrets.TelegramTarget }}
        DEBUG: true
        FORMAT: markdown
      with:
        args: |
        "🔴[${{ github.event.repository.full_name }} #${{ github.event.check_suite.id }}](${{ github.event.check_suite.url }}) *${{ github.event.check_suite.conclusion }}*.

        `${{ github.event.check_suite.head_branch }}` `${{ github.event.check_suite.head_sha }}` by *${{ github.event.check_suite.head_commit.author.name }}*

        _${{ github.event.check_suite.head_commit.message }}_"
