name: Notify

on: check_suite

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
    - name: notify to Telegram channel
      uses: appleboy/telegram-action@master
      env:
        TELEGRAM_TOKEN: ${{ secrets.TelegramBotToken }}
        TELEGRAM_TO: ${{ secrets.TelegramTarget }}
      # with:
      #   args: "A new commit has been pushed. commit sha: {{ commit.sha }}"
# GITHUB_REPOSITORY
# GITHUB_ACTOR
# GITHUB_SHA
# GITHUB_EVENT_PATH	The path of the file with the complete webhook event payload. For example, /github/workflow/event.json
